server:
  port: 8080
spring:
  application:
    name: xablau



management:
  endpoints:
    web:
      exposure:
        include:
          - '*'
  endpoint:
    health:
      show-details: ALWAYS


greeting-service:
  greeting: "teste"
  default-value: "teste"
  oss: "ossssssss"